/*
 * Copyright (c) 2026, LexxPluss Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// Drives tof_grid_assembler entirely from the golden vectors generated by the wire
// contract, so this file states no byte layout of its own. The same vectors are used by
// the SCB firmware packer; if the two implementations ever disagree, one of them fails
// here rather than on a robot.

#include <gtest/gtest.h>

#include <map>
#include <set>
#include <stdexcept>
#include <string>

#include "can_ids.hpp"
#include "tof_can_config.hpp"
#include "tof_grid_assembler.hpp"
#include "tof_report_throttle.hpp"
#include "vendor/tof_contract_vectors.h"

using lexxhard::tof_grid_assembler;
using tof_contract::FrameKind;

namespace
{

// Deliberately NOT the assigned identifiers (0x214/0x215): nothing in the assembler or
// the vectors may depend on the numbers themselves, and arbitrary values prove it.
constexpr uint32_t DATA_ID = 0x2A0;
constexpr uint32_t HEALTH_ID = 0x2A1;

const char* event_name(tof_grid_assembler::event e)
{
  switch (e)
  {
    case tof_grid_assembler::event::GRID_PUBLISHED:
      return "GRID_PUBLISHED";
    case tof_grid_assembler::event::INCOMPLETE_BY_TIMEOUT:
      return "INCOMPLETE_BY_TIMEOUT";
    case tof_grid_assembler::event::INCOMPLETE_BY_GENERATION_CHANGE:
      return "INCOMPLETE_BY_GENERATION_CHANGE";
    case tof_grid_assembler::event::DUPLICATE_CHUNK_IDENTICAL:
      return "DUPLICATE_CHUNK_IDENTICAL";
    case tof_grid_assembler::event::CONFLICTING_CHUNK:
      return "CONFLICTING_CHUNK";
    case tof_grid_assembler::event::DUPLICATE_HEALTH_IDENTICAL:
      return "DUPLICATE_HEALTH_IDENTICAL";
    case tof_grid_assembler::event::CONFLICTING_HEALTH:
      return "CONFLICTING_HEALTH";
    case tof_grid_assembler::event::FRAME_FOR_RETIRED_GENERATION:
      return "FRAME_FOR_RETIRED_GENERATION";
    case tof_grid_assembler::event::MALFORMED_HEADER:
      return "MALFORMED_HEADER";
    case tof_grid_assembler::event::HEALTH_COUNT_MISMATCH:
      return "HEALTH_COUNT_MISMATCH";
    case tof_grid_assembler::event::ORPHAN_HEALTH_TIMEOUT:
      return "ORPHAN_HEALTH_TIMEOUT";
    case tof_grid_assembler::event::SOURCE_NEVER_SEEN:
      return "SOURCE_NEVER_SEEN";
    case tof_grid_assembler::event::SOURCE_STALE:
      return "SOURCE_STALE";
    case tof_grid_assembler::event::SOURCE_RECOVERED:
      return "SOURCE_RECOVERED";
    default:
      return "?";
  }
}

const char* state_name(tof_grid_assembler::source_state s)
{
  switch (s)
  {
    case tof_grid_assembler::source_state::NEVER_SEEN:
      return "NEVER_SEEN";
    case tof_grid_assembler::source_state::HEALTHY:
      return "HEALTHY";
    case tof_grid_assembler::source_state::STALE_NOT_COMPLETING:
      return "STALE_NOT_COMPLETING";
    case tof_grid_assembler::source_state::STALE_NO_FRAMES:
      return "STALE_NO_FRAMES";
    default:
      return "?";
  }
}

struct replay_result
{
  uint32_t publish_count{ 0 };
  std::vector<tof_grid_assembler::grid> grids;
  std::map<std::string, uint32_t> events;
  std::vector<tof_grid_assembler::health_report> health_reports;
};

replay_result replay(const tof_contract::Scenario& sc, tof_grid_assembler& asm_)
{
  replay_result r;
  for (size_t i = 0; i < sc.frame_count; ++i)
  {
    const tof_contract::Frame& f = sc.frames[i];
    if (f.kind == FrameKind::kPoll)
    {
      asm_.poll(f.t_ms);
    }
    else
    {
      const uint32_t id = f.kind == FrameKind::kData ? DATA_ID : HEALTH_ID;
      if (auto g = asm_.consume(id, 8, f.bytes, f.t_ms))
      {
        ++r.publish_count;
        r.grids.push_back(*g);
      }
    }
    // Drained as we go, which also proves drain_events() empties the queue: any event
    // left behind would be counted again on the next iteration and break the multiset.
    for (const auto& d : asm_.drain_events())
      ++r.events[event_name(d.kind)];
    for (const auto& h : asm_.drain_health_reports())
      r.health_reports.push_back(h);
  }
  return r;
}

// Chunks without the closing health frame: evidence that the transport is alive, but no
// grid can complete, so nothing may clear an alarm.
void feed_chunks_only(tof_grid_assembler& a, uint64_t t)
{
  const auto& gv = tof_contract::kGridVectors[0];
  for (size_t k = 0; k < tof_grid_assembler::CHUNKS; ++k)
    a.consume(DATA_ID, 8, gv.data_frames[k].bytes, t);
  a.drain_events();
}

const tof_contract::Scenario& scenario(const char* name)
{
  for (size_t i = 0; i < tof_contract::kScenarioCount; ++i)
  {
    if (std::string(tof_contract::kScenarios[i].name) == name)
      return tof_contract::kScenarios[i];
  }
  throw std::runtime_error(std::string("no such scenario: ") + name);
}

std::string note_name(tof_grid_assembler::health_note n)
{
  switch (n)
  {
    case tof_grid_assembler::health_note::I2C_ERROR_RECOVERED:
      return "I2C_ERROR_RECOVERED";
    case tof_grid_assembler::health_note::DATA_READY_TIMEOUT_RECOVERED:
      return "DATA_READY_TIMEOUT_RECOVERED";
    case tof_grid_assembler::health_note::CHAIN_LENGTH_MISMATCH:
      return "CHAIN_LENGTH_MISMATCH";
    case tof_grid_assembler::health_note::PEER_ENUMERATION_FAILED:
      return "PEER_ENUMERATION_FAILED";
    case tof_grid_assembler::health_note::LAST_ERROR_NONZERO:
      return "LAST_ERROR_NONZERO";
    case tof_grid_assembler::health_note::HEALTH_NOTE_COUNT:
      break;
  }
  return "?";
}

std::set<std::string> notes_of(const tof_grid_assembler::health_info& h)
{
  const uint8_t bits = tof_grid_assembler::health_notes(h);
  std::set<std::string> out;
  for (uint8_t i = 0; i < static_cast<uint8_t>(tof_grid_assembler::health_note::HEALTH_NOTE_COUNT); ++i)
  {
    if (bits & static_cast<uint8_t>(1u << i))
      out.insert(note_name(static_cast<tof_grid_assembler::health_note>(i)));
  }
  return out;
}

std::set<std::string> notes_of_mask(uint8_t bits)
{
  std::set<std::string> out;
  for (uint8_t i = 0; i < static_cast<uint8_t>(tof_grid_assembler::health_note::HEALTH_NOTE_COUNT); ++i)
  {
    if (bits & static_cast<uint8_t>(1u << i))
      out.insert(note_name(static_cast<tof_grid_assembler::health_note>(i)));
  }
  return out;
}

std::string describe(const std::set<std::string>& v)
{
  std::string out;
  for (const auto& e : v)
    out += e + " ";
  return out.empty() ? "(none)" : out;
}

std::string describe(const std::map<std::string, uint32_t>& m)
{
  std::string out;
  for (const auto& kv : m)
    out += kv.first + "=" + std::to_string(kv.second) + " ";
  return out.empty() ? "(none)" : out;
}

}  // namespace

// The vendored vectors and the contract they came from must be the same version the
// firmware packer is built against. Bumping this is a deliberate act, not a side effect.
TEST(TofContract, PinnedContractVersion)
{
  EXPECT_STREQ("8a3590d30f1fa334b68a579e3f20a12620afe82bf81328cec9312b662ea1ad1f", tof_contract::kContractSha256);
  EXPECT_STREQ("2026-08-02f", tof_contract::kContractVersion);
}

TEST(TofContract, ConstantsMatchImplementation)
{
  EXPECT_EQ(tof_contract::kZones, tof_grid_assembler::ZONES);
  EXPECT_EQ(tof_contract::kChunksPerGrid, tof_grid_assembler::CHUNKS);
  EXPECT_EQ(tof_contract::kZonesPerChunk, tof_grid_assembler::ZONES_PER_CHUNK);
  EXPECT_EQ(tof_contract::kInvalidSentinel, tof_grid_assembler::INVALID_MM);
  EXPECT_EQ(tof_contract::kMaxValidMm, tof_grid_assembler::MAX_VALID_MM);
  EXPECT_EQ(tof_contract::kTimeoutMs, tof_grid_assembler::ASSEMBLY_TIMEOUT_MS);
  EXPECT_EQ(tof_contract::kSourceStaleMs, tof_grid_assembler::SOURCE_STALE_MS);
  EXPECT_EQ(tof_contract::kStartupGraceMs, tof_grid_assembler::STARTUP_GRACE_MS);
}

// Byte-exact vectors: the sixteen data frames plus health must decode back to exactly
// the grid the reference packer started from.
TEST(TofGridVectors, DecodeToTheStatedGrid)
{
  for (size_t i = 0; i < tof_contract::kGridVectorCount; ++i)
  {
    const auto& gv = tof_contract::kGridVectors[i];
    SCOPED_TRACE(gv.name);

    tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
    std::optional<tof_grid_assembler::grid> got;
    for (size_t k = 0; k < tof_grid_assembler::CHUNKS; ++k)
    {
      auto g = a.consume(DATA_ID, 8, gv.data_frames[k].bytes, 0);
      EXPECT_FALSE(g.has_value()) << "published before health at chunk " << k;
    }
    got = a.consume(HEALTH_ID, 8, gv.health_frame.bytes, 0);

    ASSERT_TRUE(got.has_value());
    EXPECT_EQ(gv.source_id, got->source);
    EXPECT_EQ(gv.generation, got->generation);
    EXPECT_EQ(gv.expected_valid_zone_count, got->health.valid_zone_count);
    for (size_t z = 0; z < tof_grid_assembler::ZONES; ++z)
      EXPECT_EQ(gv.zones_mm[z], got->zones_mm[z]) << "zone " << z;
  }
}

// Health may arrive at any point relative to the data frames, because it uses a
// different identifier and the two arbitrate independently.
TEST(TofGridVectors, HealthFirstDecodesIdentically)
{
  for (size_t i = 0; i < tof_contract::kGridVectorCount; ++i)
  {
    const auto& gv = tof_contract::kGridVectors[i];
    SCOPED_TRACE(gv.name);

    tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
    EXPECT_FALSE(a.consume(HEALTH_ID, 8, gv.health_frame.bytes, 0).has_value());
    std::optional<tof_grid_assembler::grid> got;
    for (size_t k = 0; k < tof_grid_assembler::CHUNKS; ++k)
      got = a.consume(DATA_ID, 8, gv.data_frames[k].bytes, 0);

    ASSERT_TRUE(got.has_value());
    for (size_t z = 0; z < tof_grid_assembler::ZONES; ++z)
      EXPECT_EQ(gv.zones_mm[z], got->zones_mm[z]) << "zone " << z;
  }
}

TEST(TofGridScenarios, MatchTheContract)
{
  for (size_t i = 0; i < tof_contract::kScenarioCount; ++i)
  {
    const auto& sc = tof_contract::kScenarios[i];
    SCOPED_TRACE(std::string(sc.name) + ": " + sc.description);

    tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
    const replay_result r = replay(sc, a);

    EXPECT_EQ(sc.publishes, r.publish_count > 0) << "publish_count=" << r.publish_count;
    EXPECT_EQ(sc.expected_publish_count, r.publish_count);

    if (sc.expected_zones_mm != nullptr)
    {
      ASSERT_FALSE(r.grids.empty());
      for (size_t z = 0; z < tof_grid_assembler::ZONES; ++z)
        EXPECT_EQ(sc.expected_zones_mm[z], r.grids.front().zones_mm[z]) << "zone " << z;
    }

    // Exact multiset, not "contains": an event that is not declared must not occur even
    // once, so a decoder cannot pass by emitting the right event alongside wrong ones.
    std::map<std::string, uint32_t> want;
    for (size_t e = 0; e < sc.expected_event_count; ++e)
      want[sc.expected_events[e].name] = sc.expected_events[e].count;
    EXPECT_EQ(want, r.events) << "expected [" << describe(want) << "] got [" << describe(r.events) << "]";

    const uint32_t end = sc.frames[sc.frame_count - 1].t_ms;
    if (sc.expected_state_src0 != nullptr)
    {
      EXPECT_STREQ(sc.expected_state_src0, state_name(a.source_status(0, end).state));
    }
    if (sc.expected_state_src1 != nullptr)
    {
      EXPECT_STREQ(sc.expected_state_src1, state_name(a.source_status(1, end).state));
    }
  }
}

// Frames on any other identifier belong to another subsystem and must be ignored
// silently, not counted as malformed.
TEST(TofGridAssembler, IgnoresUnrelatedCanIds)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const uint8_t payload[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };
  EXPECT_FALSE(a.consume(0x100, 8, payload, 0).has_value());
  EXPECT_EQ(0u, a.count(tof_grid_assembler::event::MALFORMED_HEADER));
}

TEST(TofGridAssembler, RejectsWrongDlc)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const uint8_t payload[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };
  EXPECT_FALSE(a.consume(DATA_ID, 7, payload, 0).has_value());
  EXPECT_EQ(1u, a.count(tof_grid_assembler::event::MALFORMED_HEADER));
}

// Leaving events in the queue would replay the whole history on every ROS spin.
TEST(TofGridAssembler, DrainEmptiesTheEventQueue)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const uint8_t bad[8] = { 0, 0x90, 0, 0, 0, 0, 0, 0 };  // source_id 9
  EXPECT_FALSE(a.consume(DATA_ID, 8, bad, 0).has_value());

  EXPECT_EQ(1u, a.drain_events().size());
  EXPECT_TRUE(a.drain_events().empty());
  // Counters are cumulative and deliberately survive the drain.
  EXPECT_EQ(1u, a.count(tof_grid_assembler::event::MALFORMED_HEADER));
}

namespace
{

// Feeds one complete grid for source 0 and returns whatever consume() emitted, with no
// poll in between.
std::map<std::string, uint32_t> feed_grid(tof_grid_assembler& a, uint64_t t)
{
  const auto& gv = tof_contract::kGridVectors[0];  // ramp, source 0, generation 0
  for (size_t k = 0; k < tof_grid_assembler::CHUNKS; ++k)
    a.consume(DATA_ID, 8, gv.data_frames[k].bytes, t);
  a.consume(HEALTH_ID, 8, gv.health_frame.bytes, t);
  std::map<std::string, uint32_t> out;
  for (const auto& d : a.drain_events())
    ++out[event_name(d.kind)];
  return out;
}

}  // namespace

// The scenario vectors cannot pin this down, because every scenario ends with a poll and
// that poll would report the recovery too, producing the same event multiset. The
// difference is real though: an operator watching a 1 Hz poll would otherwise keep seeing
// the alarm for up to a second after data resumed.
TEST(TofGridAssembler, RecoveryIsReportedAtPublicationNotAtTheNextPoll)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  a.poll(3500);  // past the startup grace, raises SOURCE_NEVER_SEEN for both sources
  a.drain_events();

  const auto events = feed_grid(a, 3600);
  EXPECT_EQ(1u, events.count("SOURCE_RECOVERED")) << "got [" << describe(events) << "]";
  EXPECT_EQ(1u, events.count("GRID_PUBLISHED"));

  // And it is not repeated by the poll that follows.
  a.poll(3700);
  EXPECT_TRUE(a.drain_events().empty());
}

TEST(TofGridAssembler, RecoveryFromStaleIsAlsoReportedAtPublication)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  feed_grid(a, 0);
  a.poll(1500);  // no traffic since t=0, so this raises SOURCE_STALE
  a.drain_events();

  tof_grid_assembler b(DATA_ID, HEALTH_ID, 0);
  feed_grid(b, 0);
  b.poll(1500);
  b.drain_events();
  // Generation 0 has been retired on b, so a second identical grid cannot republish;
  // this asserts the retirement rule holds across a stale period as well.
  const auto repeat = feed_grid(b, 1600);
  EXPECT_EQ(0u, repeat.count("GRID_PUBLISHED")) << "got [" << describe(repeat) << "]";
  EXPECT_EQ(17u, repeat.at("FRAME_FOR_RETIRED_GENERATION"));
}

// A bare SOURCE_STALE names neither the sensor nor the kind of failure, and those point
// at different faults: no frames at all is a chain, power or CAN filter problem, whereas
// frames that never complete is loss or corruption.
TEST(TofGridAssembler, WatchdogDiagnosticsNameTheSourceAndTheState)
{
  using asm_t = tof_grid_assembler;

  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  feed_grid(a, 0);  // source 0 publishes once, source 1 never appears
  a.poll(1500);     // source 0 goes stale with no frames since t=0

  bool saw_stale = false;
  for (const auto& d : a.drain_events())
  {
    if (d.kind != asm_t::event::SOURCE_STALE)
      continue;
    saw_stale = true;
    EXPECT_EQ(asm_t::SOURCE_FRONT_RIGHT, d.source);
    EXPECT_EQ(asm_t::source_state::STALE_NO_FRAMES, d.state);
  }
  EXPECT_TRUE(saw_stale);
  EXPECT_STREQ("front-right", asm_t::source_name(asm_t::SOURCE_FRONT_RIGHT));
  EXPECT_STREQ("front-left", asm_t::source_name(asm_t::SOURCE_FRONT_LEFT));
}

TEST(TofGridAssembler, StaleNotCompletingIsDistinguishedFromStaleNoFrames)
{
  using asm_t = tof_grid_assembler;
  const auto& gv = tof_contract::kGridVectors[0];

  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  // Frames keep arriving but a chunk is always missing, so nothing ever completes.
  for (uint32_t t : { 0u, 2000u, 4000u })
  {
    for (size_t k = 0; k < asm_t::CHUNKS; ++k)
    {
      if (k != 5)
        a.consume(DATA_ID, 8, gv.data_frames[k].bytes, t);
    }
  }
  a.drain_events();
  a.poll(4100);

  bool saw_stale = false;
  for (const auto& d : a.drain_events())
  {
    if (d.kind != asm_t::event::SOURCE_STALE || d.source != asm_t::SOURCE_FRONT_RIGHT)
      continue;
    saw_stale = true;
    EXPECT_EQ(asm_t::source_state::STALE_NOT_COMPLETING, d.state);
  }
  EXPECT_TRUE(saw_stale);
}

namespace
{

std::string validate(int data, int health)
{
  lexxhard::tof_can_ids ids;
  return lexxhard::validate_tof_can_ids(data, health, ids);
}

}  // namespace

TEST(TofCanConfig, AcceptsAFreeIdentifierPair)
{
  lexxhard::tof_can_ids ids;
  EXPECT_EQ("", lexxhard::validate_tof_can_ids(0x2a0, 0x2a1, ids));
  EXPECT_EQ(0x2a0u, ids.data_id);
  EXPECT_EQ(0x2a1u, ids.health_id);
}

// The single most valuable property of the shared table: nothing already on the bus can
// be handed to the ToF transport, in either direction. The two ToF rows themselves are
// the one exemption, and only in their own role — the registered data id is valid as the
// data id but refused as the health id, and vice versa.
TEST(TofCanConfig, RejectsEveryIdentifierAlreadyOnTheBus)
{
  namespace ids = lexxhard::can_ids;
  for (size_t i = 0; i < ids::kTableCount; ++i)
  {
    const int taken = static_cast<int>(ids::kTable[i].id);
    SCOPED_TRACE(taken);
    if (taken == static_cast<int>(ids::TOF_GRID_DATA))
    {
      EXPECT_EQ("", validate(taken, 0x2a1)) << "own allocation refused as the data id";
      EXPECT_NE("", validate(0x2a0, taken)) << "data allocation accepted as the health id";
    }
    else if (taken == static_cast<int>(ids::TOF_GRID_HEALTH))
    {
      EXPECT_NE("", validate(taken, 0x2a1)) << "health allocation accepted as the data id";
      EXPECT_EQ("", validate(0x2a0, taken)) << "own allocation refused as the health id";
    }
    else
    {
      EXPECT_NE("", validate(taken, 0x2a1)) << "accepted as the data id";
      EXPECT_NE("", validate(0x2a0, taken)) << "accepted as the health id";
    }
  }
}

// The assigned defaults themselves: valid as a pair, equal to the registered table rows,
// pairwise distinct 11-bit values (the same properties the firmware side asserts).
TEST(TofCanConfig, AssignedDefaultsAreValidAndRegistered)
{
  namespace ids = lexxhard::can_ids;
  lexxhard::tof_can_ids out;
  EXPECT_EQ("", lexxhard::validate_tof_can_ids(lexxhard::TOF_GRID_DATA_ID, lexxhard::TOF_GRID_HEALTH_ID, out));
  EXPECT_EQ(ids::TOF_GRID_DATA, out.data_id);
  EXPECT_EQ(ids::TOF_GRID_HEALTH, out.health_id);
  EXPECT_NE(ids::TOF_GRID_DATA, ids::TOF_GRID_HEALTH);
  EXPECT_NE(ids::TOF_GRID_DATA, ids::TOF_DROP_SENSE_RESERVED);
  EXPECT_NE(ids::TOF_GRID_HEALTH, ids::TOF_DROP_SENSE_RESERVED);
  EXPECT_LE(ids::TOF_GRID_DATA, 0x7ffu);
  EXPECT_LE(ids::TOF_GRID_HEALTH, 0x7ffu);
  EXPECT_LE(ids::TOF_DROP_SENSE_RESERVED, 0x7ffu);
}

// Swapping the pair would make this driver parse health frames as data; each value is
// only exempt in its own role, so the swap is refused like any other collision.
TEST(TofCanConfig, RejectsRoleSwappedDefaults)
{
  EXPECT_NE("", validate(lexxhard::TOF_GRID_HEALTH_ID, lexxhard::TOF_GRID_DATA_ID));
}

// 0x216 is reserved for the drop-sense frame whose contract does not exist yet; it is
// registered precisely so that nothing — including a ToF override — can take it.
TEST(TofCanConfig, RejectsTheReservedDropSenseIdentifier)
{
  const int reserved = static_cast<int>(lexxhard::can_ids::TOF_DROP_SENSE_RESERVED);
  EXPECT_NE("", validate(reserved, 0x2a1));
  EXPECT_NE("", validate(0x2a0, reserved));
}

// The override parameters are atomic as a pair, and "present but unparseable" counts as
// broken, not as absent: getParam() returning false would silently keep the default and
// mix an override with a default.
TEST(TofCanConfig, ParamPairNoOverrideIsCoherent)
{
  EXPECT_EQ("", lexxhard::check_tof_id_param_pair(false, false, true, true));
}

TEST(TofCanConfig, ParamPairFullOverrideIsCoherent)
{
  EXPECT_EQ("", lexxhard::check_tof_id_param_pair(true, true, true, true));
}

TEST(TofCanConfig, ParamPairRefusesMixedPresence)
{
  EXPECT_NE("", lexxhard::check_tof_id_param_pair(true, false, true, true));
  EXPECT_NE("", lexxhard::check_tof_id_param_pair(false, true, true, true));
}

TEST(TofCanConfig, ParamPairRefusesAnyParseFailure)
{
  EXPECT_NE("", lexxhard::check_tof_id_param_pair(true, true, false, true)) << "data present but not an integer";
  EXPECT_NE("", lexxhard::check_tof_id_param_pair(true, true, true, false)) << "health present but not an integer";
  EXPECT_NE("", lexxhard::check_tof_id_param_pair(true, true, false, false)) << "both present but neither an integer";
}

// 0x20F and 0x211 were missed by a hand-written table purely because they are declared in
// headers rather than .cpp files. They are named here so the regression stays visible
// even if the loop above is ever narrowed.
TEST(TofCanConfig, RejectsTheIdentifiersAHandWrittenTableMissed)
{
  EXPECT_NE("", validate(0x20F, 0x2a1)) << "sender_board";
  EXPECT_NE("", validate(0x211, 0x2a1)) << "sender_gpio";
  EXPECT_NE("", validate(0x204, 0x2a1)) << "ultrasonic, would hijack the USS receiver";
  EXPECT_NE("", validate(0x203, 0x2a1)) << "PGV direction, transmitted not received";
}

TEST(TofCanConfig, RejectsOutOfRangeAndFlaggedIdentifiers)
{
  EXPECT_NE("", validate(-1, 0x2a1));
  EXPECT_NE("", validate(0x800, 0x2a1)) << "above the 11-bit field";
  EXPECT_NE("", validate(0x2a0, 0x800));
  EXPECT_NE("", validate(0x2a0 | (1 << 31), 0x2a1)) << "EFF flag";
  EXPECT_NE("", validate(0x2a0 | (1 << 30), 0x2a1)) << "RTR flag";
  EXPECT_NE("", validate(0x2a0 | (1 << 29), 0x2a1)) << "ERR flag";
}

TEST(TofCanConfig, RejectsIdenticalDataAndHealthIdentifiers)
{
  EXPECT_NE("", validate(0x2a0, 0x2a0));
}

// A duplicate would silently weaken the conflict check and mean two subsystems believe
// they own one identifier.
TEST(TofCanConfig, TheSharedTableHasNoDuplicates)
{
  namespace ids = lexxhard::can_ids;
  std::map<uint32_t, int> seen;
  for (size_t i = 0; i < ids::kTableCount; ++i)
    ++seen[ids::kTable[i].id];
  for (const auto& kv : seen)
    EXPECT_EQ(1, kv.second) << "identifier 0x" << std::hex << kv.first << " listed twice";
}

// The property the previous subset test could not express. The filter and the dispatch
// now read the same rows, so a filtered identifier without a handler is impossible by
// construction — and this asserts the construction holds.
TEST(TofCanConfig, EveryReceivedIdentifierHasAHandler)
{
  namespace ids = lexxhard::can_ids;
  size_t rx = 0;
  for (size_t i = 0; i < ids::kTableCount; ++i)
  {
    const auto& e = ids::kTable[i];
    if (e.dir != ids::direction::rx)
      continue;
    ++rx;
    EXPECT_NE(ids::owner::none, e.who) << "0x" << std::hex << e.id << " is filtered but has no owner";
    EXPECT_EQ(e.who, ids::route(e.id)) << "0x" << std::hex << e.id << " routes elsewhere";
  }
  EXPECT_EQ(22u, rx) << "receive filter size changed; confirm the dispatch was updated too";
}

// A transmitted identifier must never be routed to a receiver: it would mean this driver
// was handling its own outgoing frame.
TEST(TofCanConfig, TransmittedIdentifiersAreNotRouted)
{
  namespace ids = lexxhard::can_ids;
  for (size_t i = 0; i < ids::kTableCount; ++i)
  {
    const auto& e = ids::kTable[i];
    if (e.dir != ids::direction::tx)
      continue;
    EXPECT_EQ(ids::owner::none, ids::route(e.id)) << "0x" << std::hex << e.id;
    EXPECT_TRUE(ids::is_taken(e.id)) << "0x" << std::hex << e.id << " missing from is_taken";
  }
}

// The bug this replaces: ROS_ERROR_THROTTLE inside a loop shares one timestamp across
// every source, so with both sensors down only the first is ever reported.
TEST(ReportThrottle, EverySourceReportsIndependentlyOnTheSameRound)
{
  lexxhard::report_throttle<2> t{ 5000 };
  EXPECT_TRUE(t.should_report(0, 0));
  EXPECT_TRUE(t.should_report(1, 0)) << "source 1 starved by source 0 on the same round";

  EXPECT_FALSE(t.should_report(0, 4999));
  EXPECT_FALSE(t.should_report(1, 4999));
  EXPECT_TRUE(t.should_report(0, 5000));
  EXPECT_TRUE(t.should_report(1, 5000));
}

TEST(ReportThrottle, SlotsDoNotShareAClock)
{
  lexxhard::report_throttle<2> t{ 5000 };
  EXPECT_TRUE(t.should_report(0, 0));
  EXPECT_TRUE(t.should_report(1, 3000));
  EXPECT_TRUE(t.should_report(0, 5000)) << "slot 0 is due";
  EXPECT_FALSE(t.should_report(1, 5000)) << "slot 1 reported at 3000, not yet due";
}

// A fault that clears and returns must be reported immediately, not after the remainder
// of an interval that started while it was already broken.
TEST(ReportThrottle, ClearMakesTheNextFaultReportAtOnce)
{
  lexxhard::report_throttle<2> t{ 5000 };
  EXPECT_TRUE(t.should_report(0, 0));
  EXPECT_FALSE(t.should_report(0, 100));
  t.clear(0);
  EXPECT_TRUE(t.should_report(0, 200));
}

// The persistent reporter re-states faults on a timer, so it must use the same gate as
// the edge events. Gating on "state is not HEALTHY" instead would fire on the very first
// poll after boot, when both sources are legitimately NEVER_SEEN.
TEST(TofGridAssembler, StartupGraceAppliesToTheReportableFlagToo)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);

  a.poll(100);
  for (uint8_t src = 0; src < tof_grid_assembler::SOURCE_COUNT; ++src)
  {
    const auto st = a.source_status(src, 100);
    EXPECT_EQ(tof_grid_assembler::source_state::NEVER_SEEN, st.state);
    EXPECT_FALSE(st.alarm_active) << "source " << int(src) << " reportable inside the grace";
  }

  a.poll(3001);
  for (uint8_t src = 0; src < tof_grid_assembler::SOURCE_COUNT; ++src)
    EXPECT_TRUE(a.source_status(src, 3001).alarm_active) << "source " << int(src);
}

TEST(TofGridAssembler, AlarmClearsOnRecoveryAndReRaisesOnTheNextFault)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  a.poll(3500);
  EXPECT_TRUE(a.source_status(0, 3500).alarm_active);

  feed_grid(a, 3600);
  EXPECT_FALSE(a.source_status(0, 3600).alarm_active) << "recovery must clear the alarm";

  a.poll(5000);  // no traffic since 3600, past the 1000 ms stale threshold
  const auto st = a.source_status(0, 5000);
  EXPECT_TRUE(st.alarm_active);
  EXPECT_EQ(tof_grid_assembler::source_state::STALE_NO_FRAMES, st.state);
}

// The four tests below pin the 64-bit monotonic clock. Before it, every timestamp was a
// uint32_t and the HEALTHY comparison used a signed cast to tolerate a reference that could
// sit in the future during the startup grace. That cast is what broke: once the unsigned
// difference passed 2^31 it read as negative, a long-dead source was classified HEALTHY, and
// poll() then emitted a SOURCE_RECOVERED for a sensor that had never come back.
TEST(TofGridAssembler, NoFalseRecoveryBeyondTheSignedRange)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  feed_grid(a, 0);
  a.poll(5000);  // nothing since t=0, so this raises SOURCE_STALE and latches the alarm
  a.drain_events();

  // Past 2^31 ms (~24.8 days) from the last publication. The source is still dead.
  a.poll((UINT64_C(1) << 31) + 5000);
  std::map<std::string, uint32_t> ev;
  for (const auto& d : a.drain_events())
    ++ev[event_name(d.kind)];
  EXPECT_EQ(0u, ev.count("SOURCE_RECOVERED")) << "got [" << describe(ev) << "]";

  const auto st = a.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, (UINT64_C(1) << 31) + 5000);
  EXPECT_TRUE(st.alarm_active);
  EXPECT_EQ(tof_grid_assembler::source_state::STALE_NO_FRAMES, st.state);
}

TEST(TofGridAssembler, StillStaleBeyondThe32BitWrap)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  feed_grid(a, 0);
  a.poll(5000);
  a.drain_events();

  // Past 2^32 ms (~49.7 days), and deliberately only 500 ms past it: truncated to 32 bits this
  // instant is 500, which is INSIDE SOURCE_STALE_MS of the truncated last-publication time of 0,
  // so a 32-bit clock reads the source as freshly published. Landing further past the wrap would
  // leave the truncated difference above the threshold and the test would pass on a broken
  // implementation.
  const uint64_t past_wrap = (UINT64_C(1) << 32) + 500;
  a.poll(past_wrap);
  std::map<std::string, uint32_t> ev;
  for (const auto& d : a.drain_events())
    ++ev[event_name(d.kind)];
  EXPECT_EQ(0u, ev.count("SOURCE_RECOVERED")) << "got [" << describe(ev) << "]";

  const auto st = a.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, past_wrap);
  EXPECT_TRUE(st.alarm_active);
  EXPECT_EQ(tof_grid_assembler::source_state::STALE_NO_FRAMES, st.state);
  EXPECT_GT(st.since_last_publish_ms, UINT64_C(1) << 32) << "the age itself must not wrap either";
}

// An alarm is cleared by evidence of recovery, and the only such evidence is a grid that
// actually completed. Frames arriving without completing a grid are the STALE_NOT_COMPLETING
// case, which is a fault, not a recovery.
TEST(TofGridAssembler, OnlyACompletedGridClearsTheAlarm)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  feed_grid(a, 0);
  a.poll(5000);
  a.drain_events();

  // Checked before any poll(): a poll would re-raise the alarm on a still-stale source and hide
  // an implementation that had cleared it on frame arrival.
  feed_chunks_only(a, 5100);
  EXPECT_TRUE(a.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, 5100).alarm_active) << "frames that do not "
                                                                                             "complete a grid are the "
                                                                                             "STALE_NOT_COMPLETING "
                                                                                             "fault, not a recovery";

  a.poll(5200);
  std::map<std::string, uint32_t> after_chunks;
  for (const auto& d : a.drain_events())
    ++after_chunks[event_name(d.kind)];
  EXPECT_EQ(0u, after_chunks.count("SOURCE_RECOVERED")) << "got [" << describe(after_chunks) << "]";

  // Nor does the passage of time alone.
  a.poll(9000);
  std::map<std::string, uint32_t> after_time;
  for (const auto& d : a.drain_events())
    ++after_time[event_name(d.kind)];
  EXPECT_EQ(0u, after_time.count("SOURCE_RECOVERED")) << "got [" << describe(after_time) << "]";
  EXPECT_TRUE(a.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, 9000).alarm_active);

  // The "only" is not vacuous: RecoveryIsReportedAtPublicationNotAtTheNextPoll and
  // RecoveryFromStaleIsAlsoReportedAtPublication cover the positive half, where a grid that really
  // completes does clear the alarm. This test owns the negative half.
}

// The grace is added to the budget rather than to the reference, so this boundary is the one
// place the restructured comparison could have shifted by a millisecond.
TEST(TofGridAssembler, StartupGraceBoundaryIsUnchanged)
{
  using st_t = tof_grid_assembler::source_state;
  constexpr uint64_t budget = tof_grid_assembler::STARTUP_GRACE_MS + tof_grid_assembler::SOURCE_STALE_MS;

  // A source that has produced frames but never a grid is measured from the startup time.
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  feed_chunks_only(a, 10);
  EXPECT_EQ(st_t::HEALTHY, a.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, budget).state) << "the last "
                                                                                                     "millisecond "
                                                                                                     "inside the "
                                                                                                     "budget is still "
                                                                                                     "healthy";
  EXPECT_NE(st_t::HEALTHY, a.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, budget + 1).state) << "one "
                                                                                                         "millisecond "
                                                                                                         "past it is "
                                                                                                         "not";

  // And the budget is measured from the startup time given to the constructor, not from zero.
  constexpr uint64_t late_start = 1'000'000;
  tof_grid_assembler b(DATA_ID, HEALTH_ID, late_start);
  feed_chunks_only(b, late_start + 10);
  EXPECT_EQ(st_t::HEALTHY, b.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, late_start + budget).state);
  EXPECT_NE(st_t::HEALTHY, b.source_status(tof_grid_assembler::SOURCE_FRONT_RIGHT, late_start + budget + 1).state);
}

// ---------------------------------------------------------------- C2: report throttle keying --
//
// The defect was a single ROS_WARN_THROTTLE inside the drain loop. The macro keeps its window at
// the expansion site, so every source and every reason shared one 5 s window and the first
// benign event of a window silenced the rest.

TEST(ReportSlots, EveryReasonAndSourcePairHasItsOwnSlot)
{
  using asm_t = tof_grid_assembler;
  std::set<size_t> seen;
  // Sources 0, 1, and SOURCE_COUNT for a diagnostic that cannot be attributed to either.
  for (uint8_t src = 0; src <= asm_t::SOURCE_COUNT; ++src)
  {
    for (uint8_t e = 0; e < static_cast<uint8_t>(asm_t::event::EVENT_COUNT); ++e)
    {
      const size_t slot = asm_t::report_slot(static_cast<asm_t::event>(e), src);
      EXPECT_LT(slot, asm_t::REPORT_SLOTS);
      EXPECT_TRUE(seen.insert(slot).second) << "collision at event " << int(e) << " source " << int(src);
    }
    for (uint8_t n = 0; n < static_cast<uint8_t>(asm_t::health_note::HEALTH_NOTE_COUNT); ++n)
    {
      const size_t slot = asm_t::report_slot(static_cast<asm_t::health_note>(n), src);
      EXPECT_LT(slot, asm_t::REPORT_SLOTS);
      EXPECT_TRUE(seen.insert(slot).second) << "collision at note " << int(n) << " source " << int(src);
    }
  }
  EXPECT_EQ(asm_t::REPORT_SLOTS, seen.size()) << "the slot space must be exactly covered, not merely fit";
}

// An out-of-range source shares one slot per reason rather than borrowing source 0's, so a
// malformed frame from nowhere cannot silence a real fault on a real sensor.
TEST(ReportSlots, UnattributableDiagnosticsDoNotBorrowSourceZero)
{
  using asm_t = tof_grid_assembler;
  const size_t unattributed = asm_t::report_slot(asm_t::event::MALFORMED_HEADER, asm_t::SOURCE_COUNT);
  EXPECT_NE(asm_t::report_slot(asm_t::event::MALFORMED_HEADER, asm_t::SOURCE_FRONT_RIGHT), unattributed);
  EXPECT_NE(asm_t::report_slot(asm_t::event::MALFORMED_HEADER, asm_t::SOURCE_FRONT_LEFT), unattributed);
  // Anything past the table collapses onto the same unattributed slot rather than aliasing.
  EXPECT_EQ(unattributed, asm_t::report_slot(asm_t::event::MALFORMED_HEADER, 200));
}

TEST(ReportSlots, ABenignEventDoesNotSuppressARealOneOnTheSameSource)
{
  using asm_t = tof_grid_assembler;
  lexxhard::report_throttle<asm_t::REPORT_SLOTS> th{ 5000 };
  const uint8_t src = asm_t::SOURCE_FRONT_RIGHT;

  // The firmware retransmits, so this one can be present in steady state and used to take the
  // whole window.
  EXPECT_TRUE(th.should_report(asm_t::report_slot(asm_t::event::DUPLICATE_CHUNK_IDENTICAL, src), 1000));
  // Same source, same 5 s window: both of these mean every grid is being discarded.
  EXPECT_TRUE(th.should_report(asm_t::report_slot(asm_t::event::HEALTH_COUNT_MISMATCH, src), 1001));
  EXPECT_TRUE(th.should_report(asm_t::report_slot(asm_t::event::CONFLICTING_CHUNK, src), 1002));
}

TEST(ReportSlots, TheTwoSourcesDoNotSuppressEachOther)
{
  using asm_t = tof_grid_assembler;
  lexxhard::report_throttle<asm_t::REPORT_SLOTS> th{ 5000 };
  const auto e = asm_t::event::CONFLICTING_CHUNK;
  EXPECT_TRUE(th.should_report(asm_t::report_slot(e, asm_t::SOURCE_FRONT_RIGHT), 1000));
  EXPECT_TRUE(th.should_report(asm_t::report_slot(e, asm_t::SOURCE_FRONT_LEFT), 1000));
}

TEST(ReportSlots, TheSamePairIsSuppressedInsideTheWindowAndReportsAtTheBoundary)
{
  using asm_t = tof_grid_assembler;
  lexxhard::report_throttle<asm_t::REPORT_SLOTS> th{ 5000 };
  const size_t slot = asm_t::report_slot(asm_t::event::CONFLICTING_CHUNK, asm_t::SOURCE_FRONT_RIGHT);
  EXPECT_TRUE(th.should_report(slot, 1000));
  EXPECT_FALSE(th.should_report(slot, 1000 + 4999));
  EXPECT_TRUE(th.should_report(slot, 1000 + 5000)) << "the boundary itself is due";
}

// ------------------------------------------------- C5: health diagnostics, reported not gated --

TEST(HealthNotes, ClassifiesEachFlagAndTheLastErrorByte)
{
  using note = tof_grid_assembler::health_note;
  tof_grid_assembler::health_info h;
  EXPECT_TRUE(notes_of(h).empty()) << "a clean health frame carries no notes";

  h.flags = 0x01;
  EXPECT_EQ(std::set<std::string>{ note_name(note::I2C_ERROR_RECOVERED) }, notes_of(h));
  h.flags = 0x02;
  EXPECT_EQ(std::set<std::string>{ note_name(note::DATA_READY_TIMEOUT_RECOVERED) }, notes_of(h));
  h.flags = 0x04;
  EXPECT_EQ(std::set<std::string>{ note_name(note::CHAIN_LENGTH_MISMATCH) }, notes_of(h));
  h.flags = 0x08;
  EXPECT_EQ(std::set<std::string>{ note_name(note::PEER_ENUMERATION_FAILED) }, notes_of(h));

  h = tof_grid_assembler::health_info{};
  h.last_error = 0x42;
  EXPECT_EQ(std::set<std::string>{ note_name(note::LAST_ERROR_NONZERO) }, notes_of(h));

  // Reserved bits are stripped by parse_health, so they can never become a note.
  h = tof_grid_assembler::health_info{};
  h.flags = 0x0F;
  EXPECT_EQ(4u, notes_of(h).size()) << "got [" << describe(notes_of(h)) << "]";
}

// The publish gate is deliberately unchanged: the contract states these fields do not gate,
// because under the firmware transmit obligation a grid only exists after a complete successful
// model-verified read. What must also be true is that the fact reaches diagnostics -- which is
// what the scenario's own description demands.
// Asserts on the QUEUED report, not on a classifier call against the grid. Checking
// notes_of(grid.health) would pass even with the emission deleted, because it only re-runs the pure
// function; the queue is the seam the receiver actually reads.
TEST(HealthNotes, RecoveredFlagsPublishAndAreStillEmitted)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const auto r = replay(scenario("recovered_flags_do_not_gate"), a);

  ASSERT_EQ(1u, r.publish_count) << "the grid must still publish; these flags do not gate";
  ASSERT_EQ(1u, r.health_reports.size()) << "parsed and then discarded is not diagnostic";
  const auto notes = notes_of_mask(r.health_reports.front().notes);
  EXPECT_EQ(1u, notes.count(note_name(tof_grid_assembler::health_note::I2C_ERROR_RECOVERED)))
      << "got [" << describe(notes) << "]";
  EXPECT_EQ(1u, notes.count(note_name(tof_grid_assembler::health_note::CHAIN_LENGTH_MISMATCH)))
      << "got [" << describe(notes) << "]";
}

// chain_position and boards_detected had no consumer whatsoever before this: parsed, normalised,
// compared for duplicate detection, then read by nothing. They are context on the report rather
// than notes of their own, and this is what proves they survive the trip.
TEST(HealthNotes, TheReportCarriesTheChainContextAndTheSource)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const auto r = replay(scenario("recovered_flags_do_not_gate"), a);

  ASSERT_EQ(1u, r.health_reports.size());
  const auto& h = r.health_reports.front();
  const auto& g = r.grids.front();
  EXPECT_EQ(g.source, h.source) << "a report nobody can attribute is not actionable";
  EXPECT_EQ(g.health.chain_position, h.chain_position);
  EXPECT_EQ(g.health.boards_detected, h.boards_detected);
  EXPECT_EQ(g.health.last_error, h.last_error);
}

// A clean health frame must queue nothing, or the log fills with reports that say nothing and the
// throttle spends its windows on them.
TEST(HealthNotes, ACleanHealthFrameQueuesNoReport)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const auto events = feed_grid(a, 0);
  ASSERT_EQ(1u, events.count("GRID_PUBLISHED")) << "got [" << describe(events) << "]";
  EXPECT_TRUE(a.drain_health_reports().empty());
}

// Drained exactly once, like the event queue. Left in place they would be re-reported on every ROS
// spin, which is how one condition becomes a log flood.
TEST(HealthNotes, ReportsAreDrainedOnce)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const auto r = replay(scenario("recovered_flags_do_not_gate"), a);
  ASSERT_EQ(1u, r.health_reports.size());
  EXPECT_TRUE(a.drain_health_reports().empty());
}

TEST(HealthNotes, PeerEnumerationFailureIsEmitted)
{
  tof_grid_assembler a(DATA_ID, HEALTH_ID, 0);
  const auto r = replay(scenario("peer_enumeration_failure_reported"), a);

  ASSERT_EQ(1u, r.publish_count) << "the surviving sensor still publishes";
  ASSERT_EQ(1u, r.health_reports.size());
  const auto notes = notes_of_mask(r.health_reports.front().notes);
  EXPECT_EQ(1u, notes.count(note_name(tof_grid_assembler::health_note::PEER_ENUMERATION_FAILED)))
      << "got [" << describe(notes)
      << "] -- this flag is the only way a sensor that emits nothing "
         "at all becomes visible";
}

int main(int argc, char** argv)
{
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
